tasks:
  - name: Terminal 1
    before: echo 'before script'
    init: echo 'init script'
    command: echo 'start project'

  - name: Terminal 2
    init: npm install
    command: npm run dev

ports:
  - port: 3000
    onOpen: open-preview

vscode:
  extensions:
    - jpoissonnier.vscode-styled-components
